[project]
name = "speedcopy"
version = "2.1.5"
description = "Replacement or alternative for python copyfile() utilizing server side copy on network shares for faster copying."
authors = [
    {name = "Ondrej Samohel", email = "annatar@annatar.net"}
]

license = {file = "LICENSE"}
readme = "README.md"
keywords = ["copy", "files", "filesystem", "network", "smb", "samba", "speed"]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Filesystems",
    "Topic :: Utilities",
]

dependencies = [
    "typing-extensions"
]

[project.urls]
homepage = "https://github.com/antirotor/speedcopy"
repository = "https://github.com/antirotor/speedcopy"


[project.optional-dependencies]
dev = [
    "ruff ~= 0.14",
    "pytest",
    "codespell",
    "mypy"

]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
module-name = "speedcopy"
module-root = ""
