[project]
name = "speedcopy"
version = "2.2.0"
description = "Replacement or alternative for python copyfile() utilizing server side copy on network shares for faster copying."
authors = [
    {name = "Ondrej Samohel", email = "annatar@annatar.net"}
]

license = {file = "LICENSE"}
readme = "README.md"
keywords = ["copy", "files", "filesystem", "network", "smb", "samba", "speed"]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Filesystems",
    "Topic :: Utilities",
]

dependencies = [
    "typing-extensions",
]

[project.urls]
homepage = "https://github.com/antirotor/speedcopy"
repository = "https://github.com/antirotor/speedcopy"

[project.optional-dependencies]
dev = [
    "ruff ~= 0.15",
    "pytest",
    "codespell",
    "mypy"
]

[build-system]
requires = ["uv_build>=0.9.6,<=0.11.32"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "speedcopy"
module-root = ""

[tool.ruff]
line-length = 79
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
preview = true

ignore = [
    "PTH",
    "ANN204",
    "COM812",
    "S603",
    "ERA001",
    "TRY003",
    "UP006",   # support for older python version (type vs. Type)
    "UP007",   # ..^
    "UP035",   # ..
    "UP045",   # UP045 Use `X | None` for type annotations
    "ARG002",
    "INP001",  # add `__init__.py` to namespaced package
    "S404",    # subprocess module is possibly insecure
    "PLC0415", # import must be on top of the file
    "CPY001",  # missing copyright header
    "RUF067",  # code in __init__.py__
    "D203",
    "D213",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["S101", "PLR2004"]  # allow asserts and magical values
"benchmark.py" = ["T201"]  # allow asserts and magical values
