name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/${{ github.repository }}
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Build and publish
      uses: pypa/gh-action-pypi-publish@release/v1
